-- MySQL Script generated by MySQL Workbench
-- Wed Jul 21 12:19:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_products` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  `url_image` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idproduto_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `points` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusuario_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_order` (
  `id` BIGINT NOT NULL,
  `date` DATETIME NOT NULL,
  `user_order` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpedido_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pedido_usuario1_idx` (`user_order` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`user_order`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_order_item` (
  `id` BIGINT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` VARCHAR(45) NOT NULL,
  `purchased_product` BIGINT NOT NULL,
  `order` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iditem_pedido_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_item_pedido_produto2_idx` (`purchased_product` ASC) VISIBLE,
  INDEX `fk_item_pedido_pedido1_idx` (`order` ASC) VISIBLE,
  CONSTRAINT `fk_item_pedido_produto2`
    FOREIGN KEY (`purchased_product`)
    REFERENCES `mydb`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_pedido1`
    FOREIGN KEY (`order`)
    REFERENCES `mydb`.`tb_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cart` (
  `id` BIGINT NOT NULL,
  `user_cart` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcarrinho_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_carrinho_usuario_idx` (`user_cart` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_usuario`
    FOREIGN KEY (`user_cart`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cart_item` (
  `id` BIGINT NOT NULL,
  `product_qty` INT NOT NULL,
  `cart` BIGINT NOT NULL,
  `product` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iditem_pedido_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_item_pedido_carrinho1_idx` (`cart` ASC) VISIBLE,
  INDEX `fk_item_pedido_produto1_idx` (`product` ASC) VISIBLE,
  CONSTRAINT `fk_item_pedido_carrinho1`
    FOREIGN KEY (`cart`)
    REFERENCES `mydb`.`tb_cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_produto1`
    FOREIGN KEY (`product`)
    REFERENCES `mydb`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` BIGINT NOT NULL,
  `role` VARCHAR(45) NULL,
  `users` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user_role` (
  `role_idrole` BIGINT NOT NULL,
  `usuario_idusuario` BIGINT NOT NULL,
  PRIMARY KEY (`role_idrole`, `usuario_idusuario`),
  INDEX `fk_role_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_role_has_usuario_role1_idx` (`role_idrole` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_usuario_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
